### ISSUE TITLE
App crashes when trying to open a Couchbase DB (version 1.2.1)

### ISSUE THREAD

**Issue by gmbett** [infinum/android_dbinspector#34]
I tried to use this library to see the content of a Couchbase db.

Whenever I try to open the .cblite2 DB the app crashes with the following exception:

> android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                                                                     at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                                                                     at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:318)
                                                                     at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:228)
                                                                     at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:512)
                                                                     at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
                                                                     at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
                                                                     at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:908)
                                                                     at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:878)
                                                                     at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:699)
                                                                     at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:714)
                                                                     at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:707)
                                                                     at im.dino.dbinspector.helpers.CursorOperation.execute(CursorOperation.java:20)
                                                                     at im.dino.dbinspector.helpers.DatabaseHelper.getAllTables(DatabaseHelper.java:164)
                                                                     at im.dino.dbinspector.fragments.TableListFragment.onActivityCreated(TableListFragment.java:133)
                                                                     at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1983)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                     at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                     at im.dino.dbinspector.fragments.DatabaseListFragment.onItemClick(DatabaseListFragment.java:45)
                                                                     at android.widget.AdapterView.performItemClick(AdapterView.java:334)
                                                                     at android.widget.AbsListView.performItemClick(AbsListView.java:1536)
                                                                     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3683)
                                                                     at android.widget.AbsListView$3.run(AbsListView.java:5604)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:145)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6134)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

Any idea of how to solve it ?

**Comment by reisub** [comment]
Hi @gmbett,
looks like they changed a lot more than just the extension - I will have to investigate.

**Comment by gmbett** [comment]
Ok, thank you !

**Comment by reisub** [comment]
This is fixed with 3.2.4 which will be uploaded to maven shortly and should show up at maven central in the next hours. Thanks for the bug report.

**Comment by reisub** [comment]
It should show up [here](http://repo1.maven.org/maven2/im/dino/dbinspector/) in the next hour.

**Comment by gmbett** [comment]
Awesome ! Thank you so much !
