### ISSUE TITLE
Incompatible with AppCompat 21+

### ISSUE THREAD

**Issue by TechFreak** [infinum/android_dbinspector#7]
I'm getting this error when launching the Inspector activity:

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setTitle(java.lang.CharSequence)' on a null object reference
            at im.dino.dbinspector.fragments.DatabaseListFragment.onActivityCreated(DatabaseListFragment.java:41)
            at android.app.Fragment.performActivityCreated(Fragment.java:2061)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:912)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
            at android.app.BackStackRecord.run(BackStackRecord.java:833)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
            at android.app.Activity.performStart(Activity.java:5948)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

This is how the relevant manifest entry:
<activity
            android:name="im.dino.dbinspector.activities.DbInspectorActivity"
            android:label="DbInspector"
            android:theme="@style/Theme.AppCompat.Light.DarkActionBar"
            android:icon="@drawable/ic_launcher_dbinspector">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

**Comment by reisub** [comment]
Hi @TechFreak,
thanks for taking the time to report this.
I'll what I can do about it.

**Comment by reisub** [comment]
This is fixed in version 2.0.0 which will hit maven central in the next hours.
